name: 'vdl_macros'
version: '0.2.5'
config-version: 2

clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]

require-dbt-version: ">=1.0.0"
flags:
  require_generic_test_arguments_property: true
